// Mocks generated by Mockito 5.0.14 from annotations
// in empresas/test/features/sign_in/data/repositories/sign_in_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:empresas/features/sign_in/data/datasource/sign_in_datasource.dart'
    as _i3;
import 'package:empresas/features/sign_in/data/models/investor_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeInvestorModel_0 extends _i1.Fake implements _i2.InvestorModel {}

/// A class which mocks [SignInDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInDatasource extends _i1.Mock implements _i3.SignInDatasource {
  MockSignInDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.InvestorModel> signIn(String? email, String? password) =>
      (super.noSuchMethod(Invocation.method(#signIn, [email, password]),
              returnValue:
                  Future<_i2.InvestorModel>.value(_FakeInvestorModel_0()))
          as _i4.Future<_i2.InvestorModel>);
  @override
  String toString() => super.toString();
}
